In [1]:
x = 10
a, b, c = 100, 200, 300

print(x)
print(a, b, c)

10
(100, 200, 300)

In [4]:
x = 20
print(x)
print(a, b, c)

20
(100, 200, 300)

In [3]:
type(10)

int

In [7]:
type(3.5)

float

In [10]:
a=10
b=20

a*b

200

In [12]:
a/b

0

In [13]:
a**5

100000

In [14]:
10//3

3

In [15]:
10 % 3

1

In [16]:
3+3.0

6.0

In [19]:
a, b = 7, 3.0

c = a/b
e = a**b

In [21]:
mike = 80
judy = 75
sera = 100
print((mike+judy+sera)/3)

85

In [22]:
2>1

True

In [23]:
2!=2

False

In [ ]:
num1 = int(input("입력1: "))
num2 = int(input("입력2: "))
num3 = int(input("입력3: "))

type(num1)

print(num1>65 and num2>65 and nu3m>65)

In [ ]:
x= None
print(x)
print(type(x))

In [ ]:
intro = "안녕하세요. 저는 신윤수입니다."
intro2 = "안녕하세요. 저는 주현준입니다."

In [1]:
quote = "안녕하세요. 저는 {0}이고, 키는 {1}입니다.".format("신윤수", "195")
quote

'\xec\x95\x88\xeb\x85\x95\xed\x95\x98\xec\x84\xb8\xec\x9a\x94. \xec\xa0\x80\xeb\x8a\x94 \xec\x8b\xa0\xec\x9c\xa4\xec\x88\x98\xec\x9d\xb4\xea\xb3\xa0, \xed\x82\xa4\xeb\x8a\x94 195\xec\x9e\x85\xeb\x8b\x88\xeb\x8b\xa4.'

In [2]:
"rhkdlf"*3

'rhkdlfrhkdlfrhkdlf'

In [4]:


name = "주현준"
loc = "서울"

intro = f"저는 {name}이고 {loc}에 삽니다.
print(intro)

SyntaxError: EOL while scanning string literal (<ipython-input-4-097f2dab54b0>, line 6)

In [9]:
a = "20190505chicken19000"

year = a[:4]
day = a[4:8]
menu = a[8:15]
money = a[15:]

print(year, day, menu, money)

('2019', '0505', 'chicken', '19000')

In [11]:
a = "90:30:80"

math = a[:2]
english = a[3:5]
science = a[6:]

average = (int(math)+ int(english) + int(science)) / 3
print(average)

66

In [14]:
queto = "my best career partner"
queto2 = "hello"
b=len(queto2)
print(b)

5

In [16]:
fruits = "pear, apple, grape"
fruit_list = fruits.split(',')
fruit_list

['pear', ' apple', ' grape']

In [20]:
len(fruit_list)

3

In [21]:
list_a = [1, 2, 3]
list_a

[1, 2, 3]

In [22]:
list_b = list_a
list_b

[1, 2, 3]

# 딕셔너리

In [24]:
a = {
    'name' : 'Tom',
    'english' : '80',
    'math' : '90'
}
print(a)

{'name': 'Tom', 'math': '90', 'english': '80'}

In [25]:
b = dict(name="Tom",
        english=80,
        math=99)
b

{'english': 80, 'math': 99, 'name': 'Tom'}

In [2]:
my_tuple = 1,
type(my_tuple)

tuple

In [4]:
a += 1
a -= 1
a *= 1
print(a)

NameError: name 'a' is not defined

In [5]:
from pprint import pprint

In [7]:
pprint(a_dict)

NameError: name 'a_dict' is not defined

In [10]:
a = list(range(5))
a

[0, 1, 2, 3, 4]

In [12]:
b = a.copy()
b

[0, 1, 2, 3, 4]

In [17]:
b.append(10)
b

[0, 1, 2, 3, 4, 10, 10, 10, 10]

In [18]:
print(a)
print(b)

[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 10, 10, 10, 10]

In [19]:
a = {1, 2, 3}
type(a)

set

In [20]:
s1 = set([1,2,3,])

In [21]:
# 집합 선언
s1 = {1, 2, 3}
s2 = {2, 4, 5}

In [22]:
# 교집합
print(s1 & s2)
print(s1.intersection(s2))

{2}
{2}

In [23]:
# 합집합
print(s1 & s2)
print(s1.union(s2))

{2}
{1, 2, 3, 4, 5}

In [24]:
a_str = "abcd"
'a' in a_str

True

In [2]:
s1 = discard(4)

NameError: name 'discard' is not defined

# 제어문

In [5]:
a = 10

if a==5:
    print('a는 5입니다.')

    
    if a=10:
        print('a는 10입니다.)

SyntaxError: invalid syntax (<ipython-input-5-b72d51d1037c>, line 7)

In [6]:
str_1 = "Life is too short"
str_1

'Life is too short'

In [15]:
a = input("점수1")
b = input("점수2")
c = input("점수3")

#코드작성
a = int(a)
b = int(b)
c = int(c)

if a not in range(101): or b not in range(101) or c not in range(101)
    print("잘못된 점수가 입력 되었습니다.")
elif a> 65 and b>65 and c>65:
    print("합격")
else:
    print("불합격")

SyntaxError: invalid syntax (<ipython-input-15-b83704c9cd72>, line 10)

In [12]:
a = int(input())

if a % 2 ==1:
    print ("홀수 입니다.")

    elif a

In [16]:
for i in [1, 2, 3, 4, 5]
print("리스트 현재값")

SyntaxError: invalid syntax (<ipython-input-16-3f0d4ecd57ce>, line 1)

In [17]:
a = int(input("정수를 입력해주세요:"))

for i in range(a):
    print('안녕')

정수를 입력해주세요:17
안녕
안녕
안녕
안녕
안녕
안녕
안녕
안녕
안녕
안녕
안녕
안녕
안녕
안녕
안녕
안녕
안녕

In [19]:
a = int(input("정수를 입력해주세요:"))

for i in range(a):
    print('*'*(i+1))

정수를 입력해주세요:7
*
**
***
****
*****
******
*******

In [20]:
a = int(input("정수를 입력해주세요:"))

for i in range(a):
    print('*'*(i+1))

정수를 입력해주세요:200
*
**
***
****
*****
******
*******
********
*********
**********
***********
************
*************
**************
***************
****************
*****************
******************
*******************
********************
*********************
**********************
***********************
************************
*************************
**************************
***************************
****************************
*****************************
******************************
*******************************
********************************
*********************************
**********************************
***********************************
************************************
*************************************
**************************************
***************************************
****************************************
*****************************************
******************************************
*******************************************
********************************************
*********************************************
**********************************************
***********************************************
************************************************
*************************************************
**************************************************
***************************************************
****************************************************
*****************************************************
******************************************************
*******************************************************
********************************************************
*********************************************************
**********************************************************
***********************************************************
************************************************************
*************************************************************
**************************************************************
***************************************************************
****************************************************************
*****************************************************************
******************************************************************
*******************************************************************
********************************************************************
*********************************************************************
**********************************************************************
***********************************************************************
************************************************************************
*************************************************************************
**************************************************************************
***************************************************************************
****************************************************************************
*****************************************************************************
******************************************************************************
*******************************************************************************
********************************************************************************
*********************************************************************************
**********************************************************************************
***********************************************************************************
************************************************************************************
*************************************************************************************
**************************************************************************************
***************************************************************************************
****************************************************************************************
*****************************************************************************************
******************************************************************************************
*******************************************************************************************
********************************************************************************************
*********************************************************************************************
**********************************************************************************************
***********************************************************************************************
************************************************************************************************
*************************************************************************************************
**************************************************************************************************
***************************************************************************************************
****************************************************************************************************
*****************************************************************************************************
******************************************************************************************************
*******************************************************************************************************
********************************************************************************************************
*********************************************************************************************************
**********************************************************************************************************
***********************************************************************************************************
************************************************************************************************************
*************************************************************************************************************
**************************************************************************************************************
***************************************************************************************************************
****************************************************************************************************************
*****************************************************************************************************************
******************************************************************************************************************
*******************************************************************************************************************
********************************************************************************************************************
*********************************************************************************************************************
**********************************************************************************************************************
***********************************************************************************************************************
************************************************************************************************************************
*************************************************************************************************************************
**************************************************************************************************************************
***************************************************************************************************************************
****************************************************************************************************************************
*****************************************************************************************************************************
******************************************************************************************************************************
*******************************************************************************************************************************
********************************************************************************************************************************
*********************************************************************************************************************************
**********************************************************************************************************************************
***********************************************************************************************************************************
************************************************************************************************************************************
*************************************************************************************************************************************
**************************************************************************************************************************************
***************************************************************************************************************************************
****************************************************************************************************************************************
*****************************************************************************************************************************************
******************************************************************************************************************************************
*******************************************************************************************************************************************
********************************************************************************************************************************************
*********************************************************************************************************************************************
**********************************************************************************************************************************************
***********************************************************************************************************************************************
************************************************************************************************************************************************
*************************************************************************************************************************************************
**************************************************************************************************************************************************
***************************************************************************************************************************************************
****************************************************************************************************************************************************
*****************************************************************************************************************************************************
******************************************************************************************************************************************************
*******************************************************************************************************************************************************
********************************************************************************************************************************************************
*********************************************************************************************************************************************************
**********************************************************************************************************************************************************
***********************************************************************************************************************************************************
************************************************************************************************************************************************************
*************************************************************************************************************************************************************
**************************************************************************************************************************************************************
***************************************************************************************************************************************************************
****************************************************************************************************************************************************************
*****************************************************************************************************************************************************************
******************************************************************************************************************************************************************
*******************************************************************************************************************************************************************
********************************************************************************************************************************************************************
*********************************************************************************************************************************************************************
**********************************************************************************************************************************************************************
***********************************************************************************************************************************************************************
************************************************************************************************************************************************************************
*************************************************************************************************************************************************************************
**************************************************************************************************************************************************************************
***************************************************************************************************************************************************************************
****************************************************************************************************************************************************************************
*****************************************************************************************************************************************************************************
******************************************************************************************************************************************************************************
*******************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************
*********************************************************************************************************************************************************************************
**********************************************************************************************************************************************************************************
***********************************************************************************************************************************************************************************
************************************************************************************************************************************************************************************
*************************************************************************************************************************************************************************************
**************************************************************************************************************************************************************************************
***************************************************************************************************************************************************************************************
****************************************************************************************************************************************************************************************
*****************************************************************************************************************************************************************************************
******************************************************************************************************************************************************************************************
*******************************************************************************************************************************************************************************************
********************************************************************************************************************************************************************************************
*********************************************************************************************************************************************************************************************
**********************************************************************************************************************************************************************************************
***********************************************************************************************************************************************************************************************
************************************************************************************************************************************************************************************************
*************************************************************************************************************************************************************************************************
**************************************************************************************************************************************************************************************************
***************************************************************************************************************************************************************************************************
****************************************************************************************************************************************************************************************************
*****************************************************************************************************************************************************************************************************
******************************************************************************************************************************************************************************************************

In [21]:
a = int(input("정수를 입력해주세요:"))

for i in range(a):
    print('*'*(i+3))

정수를 입력해주세요:11
***
****
*****
******
*******
********
*********
**********
***********
************
*************

In [22]:
a = int(input("정수를 입력해주세요:"))

for i in range(a):
    print('*'*(i*2))

정수를 입력해주세요:6

**
****
******
********
**********

In [23]:
a = int(input("정수를 입력해주세요:"))

for i in range(a):
    print('*'*(i-1))

정수를 입력해주세요:11


*
**
***
****
*****
******
*******
********
*********

In [24]:
a = int(input("정수를 입력해주세요:"))

for i in range(a, 0, -1):
    print('*' * (i))

정수를 입력해주세요:44
********************************************
*******************************************
******************************************
*****************************************
****************************************
***************************************
**************************************
*************************************
************************************
***********************************
**********************************
*********************************
********************************
*******************************
******************************
*****************************
****************************
***************************
**************************
*************************
************************
***********************
**********************
*********************
********************
*******************
******************
*****************
****************
***************
**************
*************
************
***********
**********
*********
********
*******
******
*****
****
***
**
*

In [25]:
# list
a = ['a', 'b', 'c']

In [30]:
x = [3, 6, 9, 20, -7, 5]

for a in x:
    print(a*10)

30
60
90
200
-70
50

In [33]:
x = [3, 6, 9, 20, -7, 5]

for a idx. val in enumerate(x):
    x[idx] *= 10

print(x)

SyntaxError: invalid syntax (<ipython-input-33-7b6dc95d1524>, line 3)

In [36]:
math = [70]
science = [80]
english = [20]

for a in math, science, english:
    print(a+10)

TypeError: can only concatenate list (not "int") to list

# for문 list, tuple, set
# for문 dictionary

In [37]:
i1 = ['a', 'b', 'c', 'd']
for i in i1:
    print(i)

a
b
c
d

In [39]:
y = ['math':70', 'science':80, 'english':20]
     
for subject in y:
     print(y[subject]+10)

SyntaxError: invalid syntax (<ipython-input-39-260c772a443c>, line 1)

In [46]:
word = ['school', 'game', 'piano', 'science', 'hotel', 'mountain']

new_word = [] # or list()

for x in word:
    if len(x)>=6:
        new_word.append(x)
        
print(new_word)

['school', 'science', 'mountain']

In [41]:
'__iter__' in dir("string")

True

In [45]:
x = int(input("정수를 입력하세요"))

for i in range(1, 10):
    print("{0} * {1} = {2}".format(x, i, x*i))

정수를 입력하세요3
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27

In [49]:


for a in range(1, 101):
    if a%3==0 and a%5==0:
        print("3과 5의 공배수")
        elif a%3==0:
            print("3의 배수")
        elif a%5==0:
            print("5의 배수")
        else:
            print("그냥 숫자")
        else:
            print(a)

SyntaxError: invalid syntax (<ipython-input-49-64a6dc44fc31>, line 4)

In [1]:
i = 0

while i<10:
    print(i)
    i+=1

0
1
2
3
4
5
6
7
8
9

In [5]:
i = 0
while i !=5:
    i = int(input("5를 입력하면 반복이 중단됩니다."))

5를 입력하면 반복이 중단됩니다.4
5를 입력하면 반복이 중단됩니다.3
5를 입력하면 반복이 중단됩니다.2
5를 입력하면 반복이 중단됩니다.1
5를 입력하면 반복이 중단됩니다.111111
5를 입력하면 반복이 중단됩니다.

ValueError: invalid literal for int() with base 10: ''

In [ ]:
i = 0
while i !=5:
    i = int(input("5를 입력하면 반복이 중단됩니다."))
    print("i.를 입력하셨습니다.")    
    print("중단")

In [ ]:
i = 0
while i !=5:
    i = int(input("5를 입력하면 반복이 중단됩니다."))
    print("중단")

In [ ]:
i = 0
while i !=5:
    i = int(input("5를 입력하면 반복이 중단됩니다."))
    print("i.를 입력하셨습니다.")    
    print("중단")

In [ ]:
num = 0
total = 0

while num!='S' or num!='s'

In [ ]:
num = '0'
total = 0

while num.upper()!='s':
    total += int(num)
    num = input("숫자를 입력하세요:")
    
print(total)

In [1]:
num = 0
total = 0

while num!='S' or num!='s'

SyntaxError: invalid syntax (<ipython-input-1-ed006e2bec51>, line 4)

In [2]:
num = '0'
total = 0

while num.upper()!='s':
    total += int(num)
    num = input("숫자를 입력하세요:")
    
print(total)

숫자를 입력하세요:1
숫자를 입력하세요:2
숫자를 입력하세요:3
숫자를 입력하세요:4
숫자를 입력하세요:5
숫자를 입력하세요:6
숫자를 입력하세요:7
숫자를 입력하세요:8
숫자를 입력하세요:9
숫자를 입력하세요:10
숫자를 입력하세요:11
숫자를 입력하세요:12
숫자를 입력하세요:13
숫자를 입력하세요:14
숫자를 입력하세요:15
숫자를 입력하세요:16
숫자를 입력하세요:17
숫자를 입력하세요:?????????????

ValueError: invalid literal for int() with base 10: '?????????????'

In [3]:
import random #random
random.random()

0.8696215424585039

In [7]:
import random #random
random.randint(1,3)

2

In [8]:
import random #random
random.random(1,3)

TypeError: random() takes no arguments (2 given)

In [9]:
import random #random
random.randint(1,3)

3

In [10]:
import random #random
random.randint(1,3)

2

In [11]:
user = 0
total = 0 
win = 0
word = ["가위", "바위", "보"]

user =  int(input("가위(1), 바위(2), 보(3)을 입력해주세요!: "))
computer = random.randit(1, 3)

while user in [1, 2, 3]:
    print("유저 : %s, 컴퓨터 : %s" % (word[user -1], word[computer - 1]))
if(user==1 and computer==3)

SyntaxError: invalid syntax (<ipython-input-11-b303df8be98f>, line 11)

In [13]:
import random #random
random.randint(1,1000)
while i !=100:

SyntaxError: unexpected EOF while parsing (<ipython-input-13-a0c4728c1f62>, line 3)

In [18]:
import random

a = []

for x in range(100):
    a.append(random.randint(1,100))

In [19]:
max_a = max(a)
print("가장 큰 수:". max_a)

AttributeError: 'str' object has no attribute 'max_a'

In [22]:
import random

a = []

for x in range(100):
    a.append(random.randint(1,100))
    
max_a = max(a)
print("가장 큰 수:", max_a)

가장 큰 수: 100

In [23]:
import random

a = []

for x in range(100):
    a.append(random.randint(1,100))
    
max_a = max(a)
print("가장 큰 수:", max_a)

가장 큰 수: 100

In [24]:
import random

a = []

for x in range(15):
    a.append(random.randint(1,100))
    
max_a = max(a)
print("가장 큰 수:", max_a)

가장 큰 수: 94

In [25]:
import random

a = []

for x in range(100):
    a.append(random.randint(1,1000))
    
max_a = max(a)
print("가장 큰 수:", max_a)

가장 큰 수: 993

In [26]:
a = [i for i in range(10) if i % 2==0]
a

[0, 2, 4, 6, 8]

In [27]:
user_dict = {keys[i]: user[i] for i in range(len(keys))}
print

NameError: name 'keys' is not defined

In [31]:
word = ['school', 'game', 'piano', 'mountain']

new_word = [w for w in word if len(w) >=6]
print(new_word)

['school', 'mountain']

In [34]:
a = [[10, 20], [30, 40], [50,60]]
b = [[2, 3], [4, 5], [6, 7]]
c = []
for x, y in a:
    for z, w in b:
        c.append([x*z, y*w])
print(c)

[[20, 60], [40, 100], [60, 140], [60, 120], [120, 200], [180, 280], [100, 180], [200, 300], [300, 420]]

In [35]:
a

[[10, 20], [30, 40], [50, 60]]

In [36]:
b

[[2, 3], [4, 5], [6, 7]]

In [37]:
for i in a:
    print(i)

[10, 20]
[30, 40]
[50, 60]

In [49]:
#for
#1.for문을 통해서 큰 리스트 인덱스를 가져온다.
for i in range(len(a)):
    print(i)
#2.각 인덱스를 통해서 a리스트와 b리스트의 작은 리스트의 값을 가져온다.
small_a = a[i]
s_a_0 = a[i][0]
s_a_1 = a[i][1]
print(small_a)
small_b = b[i]
print(small_b)
print("-"*10)
print("꺼져!"*7)

#3.a리스트와 b리스트의 값을 곱하여 [a[i] * b[i], a[i+1] * b[i+1]]
c.append([s_a_0*s_a_1])
print(c)

0
1
2
[50, 60]
[6, 7]
----------
꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!
[[20, 60], [40, 100], [60, 140], [60, 120], [120, 200], [180, 280], [100, 180], [200, 300], [300, 420], [3000], [3000], [3000]]

In [50]:
print("꺼져!"*15000)

꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져!꺼져

In [1]:

a = [[10, 20, 30], [30, 40, 30], [50,60]]
b = [[2, 3, 30], [4, 5, 30], [6, 7]]

In [10]:
c = []
#for
#1.for문을 통해서 큰 리스트 인덱스를 가져온다.
for i in range(len(a)):
    d=[]
    #2. 작은(두번째) 리스트의 인덱스를 for문으로 가져온다.,
    for j in range(len(a[i])): # [10, 20, 30]
        c.append(a[i][j] *  b[i][j])
        #
    d.append(c)
print(d)

[[20, 60, 900, 120, 200, 900, 300, 420]]

# break, continue

In [11]:
for i in range(5):
    print(i)
    
    if i == 3:
        break

0
1
2
3

In [2]:
for i in range(5):
    if i==3:
        continue
        
    print(i)

0
1
2
4

In [5]:
while True:
    num = int(input("번호를 입력하세요: "))
    if num == 1:
        break

번호를 입력하세요: 5
번호를 입력하세요: 4
번호를 입력하세요: 1

In [1]:
#11-1
num = int(input("얼마나 인사를 할까요? "))
count = 0

while True:
    if num ==count:
        break
        
        print("hi")

얼마나 인사를 할까요? 100

KeyboardInterrupt:

# 입출력

In [2]:
print("안녕하세요")

안녕하세요

In [7]:
print("제 이름은 %s입니다." % "현준")
print("제 이름은 {}입니다.".format("현준"))

제 이름은 현준입니다.
제 이름은 현준입니다.

In [8]:
file = open("my_file.txt", 'w')
file.write("This is my file.")
file.close()
#파일쓰기

In [10]:
file = open("my_file.txt", 'r')
read_str = file.read()
print(read_str)
file.close()
#파일읽기

This is my file.

In [11]:
#파일 여러줄 쓰기
target_str = """하이
방가
현준
"""
file = open("my_second_file.txt", 'w')
file.write(target_str)
file.close()

In [12]:
file = open("<파일명>", 'wt')

file = open("<파일명>", 'wb')

OSError: [Errno 22] Invalid argument: '<파일명>'

In [13]:
str_van = ".join(lines)"

In [14]:
print(str_var)

NameError: name 'str_var' is not defined

In [17]:
print("erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr")

erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr

In [18]:
with open("my_write_example.txt", "w") as f:
    f.writelines(lines)

NameError: name 'lines' is not defined

In [2]:
print('bye phyton~~~~~~~~~~~~~~:)')

bye phyton~~~~~~~~~~~~~~:)

In [5]:
import numpy as np
import pandas as pd

In [6]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [7]:
index_date = ['2018-10-17', '2018-10-18', '2018-10-19', '2018-10-20']
s3 = pd.Series([200, 195, np.nan, 205], index=index_date)
s3

2018-10-17    200.0
2018-10-18    195.0
2018-10-19      NaN
2018-10-20    205.0
dtype: float64

In [8]:
pd.date_range('2019-05-25', '2019-05-28')

DatetimeIndex(['2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28'], dtype='datetime64[ns]', freq='D')

In [9]:
pd.date_range(start='2019-05-25 10:00:00', periods=6)

DatetimeIndex(['2019-05-25 10:00:00', '2019-05-26 10:00:00',
               '2019-05-27 10:00:00', '2019-05-28 10:00:00',
               '2019-05-29 10:00:00', '2019-05-30 10:00:00'],
              dtype='datetime64[ns]', freq='D')

In [10]:
pd.date_range(start="2019-05-25", periods=8, freq='2D')

DatetimeIndex(['2019-05-25', '2019-05-27', '2019-05-29', '2019-05-31',
               '2019-06-02', '2019-06-04', '2019-06-06', '2019-06-08'],
              dtype='datetime64[ns]', freq='2D')

In [11]:
pd.date_range(start="2019-05-25 10:10", periods=8, freq='10S')

DatetimeIndex(['2019-05-25 10:10:00', '2019-05-25 10:10:10',
               '2019-05-25 10:10:20', '2019-05-25 10:10:30',
               '2019-05-25 10:10:40', '2019-05-25 10:10:50',
               '2019-05-25 10:11:00', '2019-05-25 10:11:10'],
              dtype='datetime64[ns]', freq='10S')

In [12]:

df = pd.DataFrame([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
df

    0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [14]:

df = pd.DataFrame([[10, 20, 30, 40], [40, 50, 60, 70] , [70, 80, 90, 100]])
df

    0   1   2    3
0  10  20  30   40
1  40  50  60   70
2  70  80  90  100

In [15]:

df = pd.DataFrame([[10, 20, 30, 40, 70], [40, 50, 60, 70, 80] , [70, 80, 90, 100, 102], [70, 80, 90, 100, 108]])
df

    0   1   2    3    4
0  10  20  30   40   70
1  40  50  60   70   80
2  70  80  90  100  102
3  70  80  90  100  108

In [26]:
table_data = {'연도':list(range(2010, 2020)),
              '매출액': [v**2 for i, v in enumerate(range(1,11))],
              '종업원 수': list(range(2, 30, 3))}


df = pd.DataFrame(table_data)
df

     연도  매출액  종업원 수
0  2010    1      2
1  2011    4      5
2  2012    9      8
3  2013   16     11
4  2014   25     14
5  2015   36     17
6  2016   49     20
7  2017   64     23
8  2018   81     26
9  2019  100     29

In [28]:
df.values

array([[2010,    1,    2],
       [2011,    4,    5],
       [2012,    9,    8],
       [2013,   16,   11],
       [2014,   25,   14],
       [2015,   36,   17],
       [2016,   49,   20],
       [2017,   64,   23],
       [2018,   81,   26],
       [2019,  100,   29]], dtype=int64)

In [29]:
table_data1 = {
    'A': np.arange(1, 6),
    'B': np.arange(10, 60, 10),
    'C': np.arange(100, 600, 100),
}
df1 = pd.DataFrame(table_data1)
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [31]:

table_data2 = {
    'A': [6, 7, 8],
    'B': [60, 70, 80],
    'C': [600, 700, 800],
}
df2 = pd.DataFrame(table_data2)
df2

   A   B    C
0  6  60  600
1  7  70  700
2  8  80  800

In [32]:
df1 = pd.DataFrame({'봄': [256.5, 264.3, 215.9, 223.2, 312.8],
                    '여름': [770.6, 567.5, 599.8, 387.1, 446.2],
                    '가을': [363.5, 231.2, 293.1, 247.7, 381.6],
                    '겨울': [139.3, 59.9, 76.9, 109.1, 108.1]},
                    index=['2012', '2013', '2014', '2015', '2016'])
df1

          봄     여름     가을     겨울
2012  256.5  770.6  363.5  139.3
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1

In [33]:
df1.sum()

봄     1272.7
여름    2771.2
가을    1517.1
겨울     493.3
dtype: float64

In [34]:
df1.mean()

봄     254.54
여름    554.24
가을    303.42
겨울     98.66
dtype: float64

In [35]:
df1.sum(axis=1)

2012    1529.9
2013    1122.9
2014    1185.7
2015     967.1
2016    1248.7
dtype: float64

In [36]:
df1.std()

봄      38.628267
여름    148.888895
가을     67.358496
겨울     30.925523
dtype: float64

In [37]:
df1.describe()

                봄          여름          가을          겨울
count    5.000000    5.000000    5.000000    5.000000
mean   254.540000  554.240000  303.420000   98.660000
std     38.628267  148.888895   67.358496   30.925523
min    215.900000  387.100000  231.200000   59.900000
25%    223.200000  446.200000  247.700000   76.900000
50%    256.500000  567.500000  293.100000  108.100000
75%    264.300000  599.800000  363.500000  109.100000
max    312.800000  770.600000  381.600000  139.300000

In [38]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 2012 to 2016
Data columns (total 4 columns):
봄     5 non-null float64
여름    5 non-null float64
가을    5 non-null float64
겨울    5 non-null float64
dtypes: float64(4)
memory usage: 360.0+ bytes

In [39]:
df1.loc['2013':'2016']

          봄     여름     가을     겨울
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1

In [40]:
df1.T

     2012   2013   2014   2015   2016
봄   256.5  264.3  215.9  223.2  312.8
여름  770.6  567.5  599.8  387.1  446.2
가을  363.5  231.2  293.1  247.7  381.6
겨울  139.3   59.9   76.9  109.1  108.1

In [43]:
df1.loc[['2016', '2015', '2014']]

          봄     여름     가을     겨울
2016  312.8  446.2  381.6  108.1
2015  223.2  387.1  247.7  109.1
2014  215.9  599.8  293.1   76.9

In [45]:
df2 = pd.DataFrame({
    '봄': [302.9, 256.9],
    '여름': [692.6, 1053.6],
    '가을': [307.6, 225.5],
    '겨울': [98.7, 45.6]},
    index=[2010,2011]
)
df2

          봄      여름     가을    겨울
2010  302.9   692.6  307.6  98.7
2011  256.9  1053.6  225.5  45.6

In [46]:
df1.append(df2)

          봄      여름     가을     겨울
2012  256.5   770.6  363.5  139.3
2013  264.3   567.5  231.2   59.9
2014  215.9   599.8  293.1   76.9
2015  223.2   387.1  247.7  109.1
2016  312.8   446.2  381.6  108.1
2010  302.9   692.6  307.6   98.7
2011  256.9  1053.6  225.5   45.6

In [47]:
df1 = pd.DataFrame({'Class1': [95, 92, 98, 100],
                    'Class2': [91, 93, 98, 100]})
df1

   Class1  Class2
0      95      91
1      92      93
2      98      98
3     100     100

In [2]:
df1.append(df2)

NameError: name 'df1' is not defined

In [5]:
df3 = pd.DataFrame({'Class1': [80,10], 'Class3': [50, 60]})
df3

NameError: name 'pd' is not defined

In [2]:
df1 = pd.DataFrame({'Class1': [76, 88],
                    'Class2': [100, 100]})
df1

NameError: name 'pd' is not defined

In [5]:
df1 = pd.DataFrame({'Class1': [95, 92, 98, 100],
                    'Class2': [91, 93, 98, 100]})
df1

NameError: name 'pd' is not defined

In [1]:
import random
month_list = [str(i)+'월' for i in range(1,5)]

prod_A, prod_B, prod_C, prod_D = [np.random.randint(50, 100, size=4) for i in range(4)]


df_A_B = pd.DataFrame({'판매월': month_list, 
                       '제품A': prod_A,
                       '제품B': prod_B})
df_A_B

NameError: name 'np' is not defined

In [2]:

import numpy as np
import pandas as pd

In [3]:
import random
month_list = [str(i)+'월' for i in range(1,5)]

prod_A, prod_B, prod_C, prod_D = [np.random.randint(50, 100, size=4) for i in range(4)]


df_A_B = pd.DataFrame({'판매월': month_list, 
                       '제품A': prod_A,
                       '제품B': prod_B})
df_A_B

  판매월  제품A  제품B
0  1월   81   65
1  2월   71   91
2  3월   55   97
3  4월   70   94

In [5]:
df_C_D = pd.DataFrame({'판매월': month_list,
                       '제품C': prod_C,
                       '제품D': prod_D})
df_C_D

  판매월  제품C  제품D
0  1월   53   96
1  2월   77   53
2  3월   90   86
3  4월   55   84

In [6]:
df_A_B.merge(df_C_D)

  판매월  제품A  제품B  제품C  제품D
0  1월   81   65   53   96
1  2월   71   91   77   53
2  3월   55   97   90   86
3  4월   70   94   55   84

In [7]:
prod_E, prod_F = [np.random.randint(50, 100, size=4) for i in range(2)]
df_E_F = pd.DataFrame({'판매월': ['3월', '4월', '5월', '6월'],
                       '제품E': prod_E,
                       '제품F': prod_F})
df_E_F

  판매월  제품E  제품F
0  3월   98   79
1  4월   69   69
2  5월   88   72
3  6월   55   85

In [9]:
df_A_B.merge(df_E_F, how='right')

  판매월   제품A   제품B  제품E  제품F
0  3월  55.0  97.0   98   79
1  4월  70.0  94.0   69   69
2  5월   NaN   NaN   88   72
3  6월   NaN   NaN   55   85

In [35]:
import os
BASE_DIR = os.getcwd()
DATASET_PATH = os.path.join(BASE_DIR, "data_set\\201904")
print(BASE_DIR)

C:\Users\student\실습

In [37]:
#-*- coding: utf-8 -*-
file1 = os.path.join(DATASET_PATH, '2019-04-30.csv')
print(file1)
df = pd.read_csv(file1, error_bad_lines=False, header=None, encoding='utf-8')
df

C:\Users\student\실습\data_set\201904\2019-04-30.csv

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 17: invalid start byte